STAGES = [
    {"id": "sense", "label": "Sense"},
    {"id": "analyze", "label": "Analyze"},
    {"id": "simulate", "label": "Simulate"},
    {"id": "stress_test", "label": "Stress Test"},
    {"id": "optimize", "label": "Optimize"},
    {"id": "validate", "label": "Validate"},
    {"id": "execute", "label": "Execute"},
]

SCENARIOS = {
    "leak": {
        "id": "leak", "kind": "leak", "tag": "Leak · Pipeline",
        "name": "Pressure anomaly", "loc": "Main line, Sector 4",
        "twinFocus": ["pipe4", "valve4a", "valve12"],
        "stressFails": True,
        "stages": {
            "sense": {"text": "Pressure sensor on Main 4 reads a sustained drop; flow sensor shows a corresponding rise downstream — the classic leak signature.",
                       "telemetry": [["Pressure", "2.31 → 1.62 bar"], ["Flow deviation", "+18.4%"], ["Latency", "4.1s"]]},
            "analyze": {"text": "Pattern matched against known leak signatures with high confidence. Location narrowed to a 40m segment near Valve 4A.",
                        "telemetry": [["Match confidence", "94%"], ["Segment", "Main-4 / 210-250m"]]},
            "simulate": {"text": "Digital twin projects unmitigated loss and pressure collapse across the next 2 hours if the segment is left open.",
                         "telemetry": [["Projected loss", "340 L/min"], ["2h loss est.", "~40,800 L"]]},
            "stress_test": {"text": "First plan tested: close Valve 4A outright. Simulation shows Sector 5 would drop below minimum service pressure — plan rejected.",
                            "telemetry": [["Sector 5 pressure", "1.1 bar (fail)"], ["Constraint", "min 1.8 bar"]]},
            "optimize": {"text": "Re-optimized: partially close Valve 7 and open the Valve 12 bypass to reroute supply around the isolated segment.",
                         "telemetry": [["Valve 7", "62% closed"], ["Valve 12", "opened"]]},
            "stress_retry": {"text": "Re-run with the Valve 7 + Valve 12 reroute: Sector 5 pressure holds above minimum and the leak segment is fully isolated.",
                              "telemetry": [["Sector 5 pressure", "2.04 bar (pass)"], ["Isolation", "100%"]]},
            "validate": {"text": "Full 2-hour projection confirms no other sector dips below minimum pressure and total water lost is limited to the one-time isolation volume — cleared for execution.",
                         "telemetry": [["2h projection", "all sectors nominal"], ["Residual loss", "< 50 L"]]},
            "execute": {"text": "Isolate Valve 4A, open Valve 12, throttle Valve 7. Operator notified with the full decision trail.",
                        "telemetry": [["Action", "3 valves actuated"], ["Operator alert", "sent"]]},
        },
        "metrics": [
            {"label": "Detection latency", "value": 42, "unit": "s", "max": 120},
            {"label": "Water saved", "value": 4900, "unit": "L", "max": 6000},
            {"label": "Time to contain", "value": 190, "unit": "s", "max": 300},
            {"label": "Decision validation accuracy", "value": 97, "unit": "%", "max": 100},
        ],
    },
    "drought": {
        "id": "drought", "kind": "drought", "tag": "Drought · Irrigation",
        "name": "Early wilting stress", "loc": "Grove 7, row 3-9",
        "twinFocus": ["grove7", "sprinkler7"],
        "stressFails": True,
        "stages": {
            "sense": {"text": "Bio-sensor trees in Grove 7 register an early bioelectric wilting pattern, well before any visible leaf stress. Soil moisture is trending down.",
                       "telemetry": [["Bio-signal", "early-wilt pattern"], ["Soil moisture", "11.2%"]]},
            "analyze": {"text": "Model projects visible wilting in roughly 36 hours if the current trend continues — a window to act before damage occurs.",
                        "telemetry": [["Lead time", "~36h"], ["Confidence", "89%"]]},
            "simulate": {"text": "Digital twin models root-zone moisture response to several irrigation volumes and timings.",
                         "telemetry": [["Scenarios tested", "5"], ["Target moisture", "24-28%"]]},
            "stress_test": {"text": "First plan tested: single long irrigation pulse. Simulation flags runoff beyond the root zone — water would be wasted.",
                            "telemetry": [["Runoff risk", "high (fail)"], ["Uptake efficiency", "51%"]]},
            "optimize": {"text": "Re-optimized into a micro-pulse schedule: five short cycles a day at low flow, matched to root uptake rate.",
                         "telemetry": [["Cycles", "5 / day"], ["Flow per cycle", "low"]]},
            "stress_retry": {"text": "Re-run the micro-pulse schedule: root zone reaches target moisture with no measurable runoff.",
                              "telemetry": [["Runoff", "0% (pass)"], ["Uptake efficiency", "93%"]]},
            "validate": {"text": "Cross-checked against the 48-hour weather forecast — no rain expected, so the full schedule is confirmed as the right total water volume for the grove.",
                         "telemetry": [["Forecast check", "dry, 48h"], ["Total volume", "within budget"]]},
            "execute": {"text": "Activate underground sprinklers in Grove 7 on the micro-pulse schedule for the next 24 hours.",
                        "telemetry": [["Zone", "Grove 7"], ["Duration", "24h schedule"]]},
        },
        "metrics": [
            {"label": "Water use vs fixed schedule", "value": 58, "unit": "% less", "max": 100},
            {"label": "Stress predicted ahead of visible wilt", "value": 36, "unit": "h", "max": 48},
            {"label": "Root-zone uptake efficiency", "value": 93, "unit": "%", "max": 100},
            {"label": "Decision validation accuracy", "value": 96, "unit": "%", "max": 100},
        ],
    },
    "fire": {
        "id": "fire", "kind": "fire", "tag": "Fire risk · Forest",
        "name": "Rising ignition risk", "loc": "Forest, Sector 2",
        "twinFocus": ["forest2", "drone1", "drone2"],
        "stressFails": True,
        "stages": {
            "sense": {"text": "Canopy bio-sensors register a smoke-precursor signal alongside rising heat and falling humidity across Sector 2.",
                       "telemetry": [["Humidity", "31%, falling"], ["Heat trend", "+2.4°C/h"]]},
            "analyze": {"text": "Ignition probability is climbing faster than the historical baseline for this wind and humidity combination.",
                        "telemetry": [["Ignition probability", "rising"], ["Wind", "14 km/h NE"]]},
            "simulate": {"text": "Digital twin runs a fire-spread model for the current wind vector and canopy dryness.",
                         "telemetry": [["Spread model runs", "3"], ["Worst-case radius", "1.2 km / 30 min"]]},
            "stress_test": {"text": "First plan tested: mist line only. Under sustained wind above 18 km/h, simulated containment fails.",
                            "telemetry": [["Containment @ mist-only", "fails above 18 km/h"]]},
            "optimize": {"text": "Escalated plan: mist line plus two solar drones pre-positioned to the windward edge of Sector 2.",
                         "telemetry": [["Drones assigned", "2"], ["Mist line", "armed"]]},
            "stress_retry": {"text": "Re-run the combined mist + drone plan: containment holds across the current and forecast wind range.",
                              "telemetry": [["Containment probability", "96% (pass)"]]},
            "validate": {"text": "Cross-checked against the fire department's current response time and crew availability — the automated plan is confirmed compatible with responders already inbound.",
                         "telemetry": [["Dept ETA", "11 min"], ["Plan compatibility", "confirmed"]]},
            "execute": {"text": "Dispatch both drones, activate the perimeter mist line, and alert the local fire department pre-emptively.",
                        "telemetry": [["Drones", "dispatched"], ["Fire dept alert", "sent"]]},
        },
        "metrics": [
            {"label": "Containment probability", "value": 96, "unit": "%", "max": 100},
            {"label": "Lead time before ignition", "value": 22, "unit": "min", "max": 40},
            {"label": "Response initiated pre-flame", "value": 100, "unit": "%", "max": 100},
            {"label": "Decision validation accuracy", "value": 95, "unit": "%", "max": 100},
        ],
    },
    "pump": {
        "id": "pump", "kind": "pump", "tag": "Predictive · Pump station",
        "name": "Bearing degradation", "loc": "Pump Station B",
        "twinFocus": ["pumpB", "pumpA", "pumpC"],
        "stressFails": True,
        "stages": {
            "sense": {"text": "Vibration and thermal sensors on Pump B, bearing 3, show a slow drift consistent with early bearing wear.",
                       "telemetry": [["Bearing temp", "71.4°C, rising"], ["Vibration", "above baseline"]]},
            "analyze": {"text": "Failure-window model predicts a 6-9 day horizon before bearing 3 is likely to fail outright.",
                        "telemetry": [["Failure window", "6-9 days"], ["Confidence", "91%"]]},
            "simulate": {"text": "Digital twin models network load if Pump B is throttled now versus run to failure and replaced reactively.",
                         "telemetry": [["Scenarios", "throttle-now vs run-to-failure"]]},
            "stress_test": {"text": "First plan tested: shift Pump B's full load to Pumps A and C. At peak demand, Pump A's simulated temperature exceeds its safe limit — fails.",
                            "telemetry": [["Pump A temp @ peak", "over limit (fail)"]]},
            "optimize": {"text": "Re-optimized load split: reduce Pump B to 60% load, distribute the remainder more evenly across A and C.",
                         "telemetry": [["Pump B load", "-40%"], ["Split", "balanced A/C"]]},
            "stress_retry": {"text": "Re-run at peak demand with the revised split: all three pumps stay within safe thermal limits.",
                              "telemetry": [["Pump A temp @ peak", "within limit (pass)"]]},
            "validate": {"text": "Confirmed against the full daily demand curve, not just the worst-case peak — thermal margins hold at every hour.",
                         "telemetry": [["24h demand curve", "checked"], ["Min margin", "8%"]]},
            "execute": {"text": "Throttle Pump B to 60% load, schedule a technician visit inside the failure window, and order the replacement bearing.",
                        "telemetry": [["Pump B", "throttled to 60%"], ["Maintenance", "scheduled"]]},
        },
        "metrics": [
            {"label": "Unplanned downtime avoided", "value": 100, "unit": "%", "max": 100},
            {"label": "Failure predicted ahead of event", "value": 7, "unit": "days", "max": 10},
            {"label": "Network capacity maintained", "value": 100, "unit": "%", "max": 100},
            {"label": "Decision validation accuracy", "value": 94, "unit": "%", "max": 100},
        ],
    },
    "industrial": {
        "id": "industrial", "kind": "industrial", "tag": "Green Box · Aviation",
        "name": "Engine vibration anomaly", "loc": "In-flight, engine mount NPU",
        "twinFocus": ["engine", "groundCSE", "warehouse", "drone3"],
        "stressFails": True,
        "stages": {
            "sense": {"text": "The Green Box's on-engine NPU flags a vibration signature consistent with early bearing wear — processed fully on-device, no cloud round-trip.",
                       "telemetry": [["Edge decision latency", "7.5 ms"], ["Signal", "vibration + thermal drift"]]},
            "analyze": {"text": "Pattern matches a known bearing-wear precursor. The system estimates a failure window and drafts a spare-part need before the aircraft lands.",
                        "telemetry": [["Failure window", "~40 flight hours"], ["Confidence", "91%"]]},
            "simulate": {"text": "Digital twin models two notification paths: request the part now via satellite, or wait and hand off once the aircraft nears the ground station.",
                         "telemetry": [["Paths modeled", "2"], ["Aircraft position", "310 km out"]]},
            "stress_test": {"text": "First plan tested: dispatch the drone immediately from the warehouse. Simulation shows it would enter the airport's restricted 20km ATC zone before clearance — plan rejected.",
                            "telemetry": [["ATC geofence", "violated (fail)"], ["Zone radius", "20 km"]]},
            "optimize": {"text": "Re-optimized: send a short oneM2M spare-part request now over the aircraft's existing SATCOM link, but hold the drone launch until the aircraft crosses the geofence into ground-network range.",
                         "telemetry": [["Request channel", "existing SATCOM (oneM2M)"], ["Drone hold", "until geofence cross"]]},
            "stress_retry": {"text": "Re-run the revised plan: the request reaches the ground CSE in time, and the drone's timed launch clears ATC restrictions while still landing the part before wheels-down.",
                              "telemetry": [["ATC compliance", "pass"], ["Part ready by", "landing"]]},
            "validate": {"text": "Cross-checked against the maintenance crew's shift schedule — the part and a technician will both be ready at the gate, not just one of them.",
                         "telemetry": [["Technician shift", "aligned"], ["Part + crew ready", "confirmed"]]},
            "execute": {"text": "Green Box relays the oneM2M spare-part request over SATCOM; the ground CSE issues a dispatch order; the drone launches on a timed schedule from the warehouse to the gate.",
                        "telemetry": [["Dispatch order", "issued"], ["Drone", "launched on timer"]]},
        },
        "metrics": [
            {"label": "Edge decision latency", "value": 7.5, "unit": "ms", "max": 20},
            {"label": "Spare part ready before landing", "value": 45, "unit": "min lead", "max": 60},
            {"label": "Est. downtime cost avoided", "value": 460, "unit": "$K/incident", "max": 550},
            {"label": "Decision validation accuracy", "value": 93, "unit": "%", "max": 100},
        ],
    },
}
